In [1]:
import numpy as np 
from numpy.linalg import norm, det, inv, cond, matrix_rank
from numpy import arccos, dot

import scipy.linalg as la

In [2]:
# create a row vector 
"""vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], [2], [3], [4]])
print(vector_row.shape)
print(vector_column.shape)
"""


'vector_row = np.array([[1, -5, 3, 2, 4]])\nvector_column = np.array([[1], [2], [3], [4]])\nprint(vector_row.shape)\nprint(vector_column.shape)\n'

In [ ]:
# transpose the row vector we defined above 
"""new_vector = vector_row.T
print("new_vector", new_vector)
norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)
print('L_1 is: %.1f'%norm_1)
print('L_2 is: %.1f'%norm_2)
print('L_inf is: %.1f'%norm_inf)
"""



In [3]:
# calculate angle
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
u = v + w
d = dot(v,w.T)
print(d)
print(u)
theta = \
    arccos(dot(v, w.T)/(norm(v)*norm(w)))
#print(theta)

[[101]]
[[12 14 15]]


In [4]:
# show that a(v+w) = av + aw
a = np.array([[1,8,3]])
first = a*(v + w)
second = (a*v) + (a*w)
print(first)
print(second)

[[ 12 112  45]]
[[ 12 112  45]]


In [5]:
np.cross(v,w)

array([[  93, -114,   32]])

In [6]:
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
print(np.cross(v, w))

[[ 0  0 -6]]


In [7]:
# linear combination
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])
x = 3*v-2*w+4*u
print(x)

[[-8 -1  4]]


In [3]:
# matrices
# calculate matrix products 
P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])
print(P)
print(Q)
print(np.dot(P, Q))
# print(np.dot(Q,P)) - 

[[1 7]
 [2 3]
 [5 0]]
[[2 6 3 1]
 [1 2 3 4]]
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [7]:
# determinant of matrix M 
M = np.array([[0,2,1,3], 
             [3,2,8,1], 
             [1,0,0,3],
             [0,3,2,1]])
print('M:\n', M)

print('Determinant: %.1f'%det(M))


M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0


In [8]:
# calculate identity matrix 
I = np.eye(4)
print('I:\n', I)
# get dot of i by M 
print('M*I:\n', np.dot(M, I))

I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


In [10]:
# can calculate if a matrix is singular by computing it's determinant - if determinant is 0 then matrix is singular
# compute inverse of M 
print('Inv M:\n', inv(M))


Inv M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]


In [13]:
# show that matrix P has det value of 0 and has no inverse 
P = np.array([[0,1,0],
              [0,0,0],
              [1,0,1]])
print('det(p):\n', det(P))


det(p):
 0.0


In [15]:
# compute condition number and rank for this matrix 
A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1]])

print('Condition number:\n', cond(A))
print('Rank:\n', matrix_rank(A))

Condition number:
 4.048917339522305
Rank:
 3


In [16]:
# calculate augmented matrix[A, y]
y = np.array([[1], [2], [1]])
A_y = np.concatenate((A, y), axis = 1)
print('Augmented matrix:\n', A_y)

Augmented matrix:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]


In [ ]:
# Linear Transformations 
# f is linear transformation if... 
# f(ax+by)=af(x)+bf(y)


In [ ]:
# https://pabloinsente.github.io/intro-linear-algebra
# https://personal.math.ubc.ca/~pwalls/math-python/linear-algebra/linear-algebra-scipy/

In [2]:
# 1d array 
a = np.array([1,2,-3,1])

In [3]:
a.ndim # number of dimensions

1

In [4]:
a.shape

(4,)

In [8]:
# 2 day array(matrix)
M = np.array([[1,2],[3,7],[-1,5]])
M.ndim

2

In [9]:
M.shape

(3, 2)

In [10]:
col = M[:,1] 
